<?php

namespace app\index\model;


use think\Db;
use think\Model;

class Commodity extends Model
{
  public function selectCommodity($cname)
  {
    return $this->whereOr([
      'cname' => $cname
    ])->find(); // TODO: Change the autogenerated stub
  }

  public function seTypeid($id)
  {
    return Db::name('commodity')->where(['typeid' => $id])->select();
  }
  public function seCid($id)
  {
    return Db::name('commodity')->field('cid',true)->where(['typeid' => $id])->select();
  }

  public function seAll()
  {
    return Db::name('commodity')->field(true)->order('id')->paginate(8);
  }

  public function seCommodity($value)
  {
    return Db::name('commodity')->field(true)->where('cname|specification', 'like', '%' . $value . '%')->select();
  }

  public function seDiscount()
  {
    return Db::name('commodity')->field(true)->where('discount', '>', 0)->select();
  }

  public function selectDiscount($id)
  {
    return Db::name('commodity')->field('discount')->where(['id' => $id])->select();
  }

  public function seData($id)
  {
    return Db::name('commodity')->field(true)->where(['id' => $id])->select();
  }
  public function deleteNum($cid, $num)
  {
    return Db::name('commodity')->where('id', $cid)->update(['number' => $num]);
  }
  public function deleteAll($id)
  {
    return Db::name('commodity')->field('id', true)->where(['typeid' => $id])->delete(true);
  }
}