<?php


namespace app\index\model;

use think\Db;
use think\Model;

class Type extends Model
{
  public function selectTname($typename)
  {
    return $this->whereOr([
      'typename' => $typename
    ])->find(); // TODO: Change the autogenerated stub
  }
  public function selectAll(){
    return Db::name('type')->select();
  }

}