<?php


namespace app\index\model;


use  think\Db;
use think\Model;

class User extends Model
{
  public function register($data)
  {
    return Db::name('user')->field(true)->insert($data);
  }

  public function login($username, $password)
  {
    return Db::name('user')->field('password', true)->where([
      'username' => $username,
      'password' => md5($password),
    ])->find(); //select结果是二维数组,find结果是一条数据
  }

  public function se($username, $phone, $email)
  {
    return $this->whereOr([
      'username' => $username,
      'phone' => $phone,
      'email' => $email,
    ])->find(); // TODO: Change the autogenerated stub
  }

  public function uppw($data, $id)
  {
    return Db::name('user')->field(true)->where($id)->update(['password' => md5($data['password'])]);
  }

  public function seid($username)
  {
    return Db::name('user')->field('id', false)->where([
      'username' => $username,
    ])->find();
  }

  public function sepw($username)
  {
    return Db::name('user')->where([
      'username' => $username,
    ])->field('password', false)->find(); // TODO: Change the autogenerated stub
  }

  public function seuser($username)
  {
    return Db::name('user')->where([
      'username' => $username
    ])->field('password', true)->find();
  }

  public function updateUser($data)
  {
    return $this->isUpdate(true)->data($data)->save();
  }

  public function deleteSp($id)
  {
    return Db::name('spcart')->field('id', true)->where(['id' => $id])->delete(true);
  }

  public function deleteCollect($id)
  {
    return Db::name('collect')->field('id', true)->where(['id' => $id])->delete(true);
  }

  public function seuid($username)
  {
    return Db::name('user')->field(true)->where([
      'username' => $username
    ])->find();
  }
  public function deleteAll($id){
    return Db::name('pay')->where(['uid' => $id])->delete(true);
  }
}